### ISSUE TITLE
download fwa.zip

### ISSUE THREAD

**Issue by sebdalgarno** [smnorris/fwapg#12]
This isn't exactly an issue with your scripts but I'm having trouble downloading the fwa.zip file required before running your scripts.

When I run
```
wget https://geobc.s3-us-west-2.amazonaws.com/FWA.zip
```
 I get 
```
--2020-05-05 20:01:35--  https://geobc.s3-us-west-2.amazonaws.com/FWA.zip
Resolving geobc.s3-us-west-2.amazonaws.com (geobc.s3-us-west-2.amazonaws.com)... 52.218.251.41
Connecting to geobc.s3-us-west-2.amazonaws.com (geobc.s3-us-west-2.amazonaws.com)|52.218.251.41|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-05-05 20:01:36 ERROR 403: Forbidden.
```

Can you confirm that you are still able to download from that link?
Cheers!

**Comment by smnorris** [comment]
Sorry, should work now - I neglected to update the access control to `public-read` last time I refreshed the file. 

According to GeoBC I should probably refresh monthly but so far my schedule is pretty random.

**Comment by sebdalgarno** [comment]
thanks @smnorris! 

By the way, I am the author of fwabc R package (haven't worked on it in a while, very experimental). We are going to develop a new R package this year that takes advantage of this postgres approach rather than WFS via databc. We are thinking of putting a postegres database on AWS so that our users (and us) don't have to interact with the database locally. 

Thanks for all your work on this it's extremely helpful

**Comment by smnorris** [comment]
👍  PRs on SQL functions are very welcome, everything I've done has been ad-hoc.

I'd also encourage you to request that a similar package be posted by GeoBC/DataBC... just so I'm not the only one asking. 

Also, I created a hosted db for much the same reason. It is slightly dated but you can try it out if you like:

api: https://hillcrestgeo.ca/fwa/ 
test map: https://hillcrestgeo.ca/projects/mvt_test/
