### ISSUE TITLE
JSON and view buttons not working for fwapg.fwa_stream_networks_sp

### ISSUE THREAD

**Issue by joethorley** [smnorris/fwapg#125]
<img width="1249" alt="Screen Shot 2022-11-24 at 18 22 11" src="https://user-images.githubusercontent.com/613671/203887678-947002dc-e9cb-49ec-93b9-87b491cd51e1.png">

**Comment by smnorris** [comment]
This is pretty interesting, I don't grant the pg_fs user access to that schema or that table, it should never show up.
I did do some manual shuffling of tables last week as a shortcut for applying an update without running a full load - the table got renamed and moved from one schema to another - and it retained the pg_fs usage grant.
