### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by heckstra** [smnorris/fwapg#159]
In the README, quickstart step 2 provides this db URL:
export DATABASE_URL=postgres://username:password@localhost:5432/fwapg

I got this error:
`sqlalchemy.exc.NoSuchModuleError:` Can't load plugin: sqlalchemy.dialects:postgres`

After some googling, it worked when I changed postgres:// to postgresql:// in the DATABASE_URL

**Comment by smnorris** [comment]
Thank you! Good to have more eyes on this.
