### ISSUE TITLE
add new linear referencing functions for pg_featureserv

### ISSUE THREAD

**Issue by smnorris** [smnorris/fwapg#25]
1. Return a point at specified meters upstream 
2. Return multiple points at specified distance along stream with labels (0 starting at mouth and moving up)

I think a linear function would be useful too (provided a blue_line_key and two measures, return a single feature representing the stream between them) - but that is out of scope for now.

**Comment by smnorris** [comment]
Proposed functions:

1. `FWA_LocateAlong(blue_line_key, downstream_route_measure)` - return a point geometry, basically just a wrapper around https://postgis.net/docs/ST_LocateAlong.html
2. `FWA_LocateAlongInterval(blue_line_key, interval)` - return a table of point geometries located along the stream at set interval (m)

@sebdalgarno, @joethorley - let me know if these names/parameters don't work (and any comments on the `FWA_NearestStream` -> `FWA_IndexPoint` name change in #27 are welcome too)

**Comment by sebdalgarno** [comment]
I think these names should work. We can always rename them in the fwapgr package, if need be.
In the FWA_LocateAlongInterval function, is it possible for you to return a 'Label' (or 'Distance'?) column along with the geometries in the returned table? i.e. some way for the user to know the order of the points...so at interval of 100m, Label would be 0, 0.1, 0.2, 0.3 etc. with default units in km starting at the most downstream point

**Comment by sebdalgarno** [comment]
actually this column could be called Rkm or RiverKm

**Comment by sebdalgarno** [comment]
if that seems too specific, perhaps there could be a third function FWA_Rkm that makes use of FWA_LocateAlongInterval and returns the Rkm labels...

**Comment by smnorris** [comment]
Sure, a third FWA_Rkm func is no problem.  
Maybe easier is that `FWA_LocateAlongInterval` has a label / distance column (in metres) that you divide by 1000 in an FWA_Rkm R function?

**Comment by sebdalgarno** [comment]
Yes I think that is the best option. We will just have an R function that creates the Rkm column from Distance (in meters)

**Comment by smnorris** [comment]
I've generalized it a tiny bit more - rather than return distance, the function returns an index - multiply that index by the interval length to get Rkm.

**Comment by smnorris** [comment]
fwa_locatealonginterval is live. The default `limit` is low, so the server doesn't bog down on big features. Explicitly set your limit high if it is a long river. I think I have to adjust the return type in `fwa_locatealong`, the function is on the server but not showing up in the function list.

https://www.hillcrestgeo.ca/fwapg/functions/fwa_locatealonginterval/items.html?blue_line_key=354153927&limit=500

**Comment by smnorris** [comment]
Looks like the above request doesn't return a point at index=0, I'll fix. 
index=0 does get returned if the starting point isn't 0 - my check on whether the location actually exists is too strict.
