### ISSUE TITLE
FWA_LocateAlongInterval - add max measure for interval

### ISSUE THREAD

**Issue by smnorris** [smnorris/fwapg#36]
https://github.com/poissonconsulting/fwatlasbc/issues/23

- default to max measure for the given stream
- warn user if provided max is greater than max in db 

Not sure how/if pg_featureserv can handle warnings but otherwise this should be simple.

**Comment by joethorley** [comment]
Yes this would be awesome.

**Comment by smnorris** [comment]
Note that when provided a measure greater than what exists in the database, the database raises the error `ERROR: Input end_measure value does not exist in FWA` but pg_featureserv just responds with `Unable to read data from: fwa_locatealonginterval`
