### ISSUE TITLE
FWA_WatershedAtMeasure performance

### ISSUE THREAD

**Issue by smnorris** [smnorris/fwapg#4]
Unsurprisingly, bigger areas take longer to build:

Sooke River @ mouth:
```
time psql -c "SELECT wscode_ltree FROM fwa_refinedwatershed(354153927, 0)"
real	0m1.366s
user	0m0.009s
sys	0m0.010s
```

Cowichan River @ 7.2km:
```
time psql -c "SELECT wscode_ltree FROM fwa_refinedwatershed(354155148, 7200)"
real	0m4.057s
user	0m0.007s
sys	0m0.006s
```

Running the Fraser River at measure of 1000m takes too long to wait for. 

Fix for now is to adjust the query to use `fwa_assessment_watersheds_poly` as pre-aggregated areas. As a test, this takes ~47s for Fraser River at measure 1000m. This is acceptable for current use case, but is there a faster way to get the outer edge of the geometry collection? Also, using the assessment watersheds is only quick if *only* using that layer, there doesn't seem to be a quick way to select upstream assessment watersheds and then tack on the first order watersheds that are not upstream of that first selection.

A cache of some kind is probably the way to go but using a built in postgis function would be nice.

**Comment by smnorris** [comment]
One option to investigate is using a topology so that the external ring is quickly selectable

**Comment by smnorris** [comment]
Another option to evaluate is creating a lookup that relates the fundamental watersheds to the assessment watersheds. This should allow for selecting upstream assessment watersheds and then quickly tacking on the first order watersheds that are not upstream of that first selection.

**Comment by smnorris** [comment]
Fixed for very large watersheds by using assessment watersheds / watershed groups / larger basins as pre-aggregated shapes. However, all these joins slow down results for smaller watersheds. We might be able to add a check in the function to only try and join to the larger features if there is a result returned. If this works, the `fwa_watershedrefined.sql` function will get very long, it may be worth splitting into several functions?

**Comment by smnorris** [comment]
For speed and common use case, we could pull the wsd boundary from `fwa_named_watersheds` if the provided `downstream_route_measure`= 0 and the provided `blue_line_key` feature has a `gnis_name`. 

I'm not sure that looking up (complete) watershed polygons by `blue_line_key` is the best way to go though, watershed code or name seems more intuitive.

**Comment by dr-jts** [comment]
I'm hoping to eventually expose the JTS/GEOS OverlayNG Polygon Coverage Union capability in PostGIS. That should make unioning vector-clean sets of polygons *much* faster.  (See the last section in [this blog post](http://lin-ear-th-inking.blogspot.com/2020/06/jts-overlayng-noding-strategies.html) for details).

**Comment by smnorris** [comment]
Nice! I knew you have been working on that but hadn't seen that particular blog post - and didn't know that performance gains would trickle down into st_union as well.  Looking forward to it.

**Comment by smnorris** [comment]
coming soon... https://www.bostongis.com/blog/index.php?/archives/275-Waiting-for-PostGIS-3.1-ST_Subdivide-and-other-function-support-with-fixed-precision.html

**Comment by dr-jts** [comment]
Yes, indeedy!  It's been a long wait, but it's looking good.

**Comment by smnorris** [comment]
With postgis 3.1, using current `FWA_WatershedAtMeasure` (uses assessment watersheds as pre-aggregation) things are looking pretty reasonable. I'm going to combine a few of the watershed issues into one.

```
fwapg=# select postgis_full_version();
                                                                       postgis_full_version
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.1.2 cbe925d" [EXTENSION] PGSQL="130" GEOS="3.9.1-CAPI-1.14.2" PROJ="7.2.1" LIBXML="2.9.12" LIBJSON="0.15" LIBPROTOBUF="1.4.0" WAGYU="0.5.0 (Internal)"
(1 row)


$ time psql -c "SELECT st_area(geom) / 10000 as area_ha FROM postgisftw.fwa_watershedatmeasure(354153927, 0)"
      area_ha
-------------------
 34169.69603558175
(1 row)

real	0m1.322s
user	0m0.006s
sys	0m0.006s

$ time psql -c "SELECT st_area(geom) / 10000 as area_ha FROM postgisftw.fwa_watershedatmeasure(354155148, 7200)"
      area_ha
-------------------
 82890.96232187672
(1 row)


real	0m1.946s
user	0m0.006s
sys	0m0.006s
```
