### ISSUE TITLE
FWA_WatershedAtMeasure output type

### ISSUE THREAD

**Issue by smnorris** [smnorris/fwapg#40]
Currently the function `RETURNS TABLE`. This makes sense for the typical case where just requesting a single watershed, especially via the current api.

When using the db directly, it would be nice to use the function to generate watersheds within a more general/typical context.

eg - I have a bunch of IDs and want a set of results with watersheds for each:

```
SELECT
 stream_crossing_id,
 downstream_route_measure,
 blue_line_key,
 FWA_WatershedAtMeasure(blue_line_key, downstream_route_measure)
FROM bcfishpass.crossings
WHERE stream_crossing_id in (50152,62515,50181,50185,50261,62423,62516,197533,197534,197542,197555);
```
This gives a result like this, the output from the function is a nested table / values with watershed codes, refine method and geom:
```
62515	112	356547712	(300.625474.584724.233916.539602,300.625474.584724.233916.539602,444.72,DEM,<geom>)
```
Returning the watershed codes and area isn't really necessary, but returning the refine method as well as the output geom definitely is - perhaps return an array holding these two values rather than a table would be easier to work with?

**Comment by smnorris** [comment]
A table returning function does not seem to be the best choice, the func always returns one row.
Array should work, it could also return `RECORD` or a custom type:
https://www.postgresql.org/docs/12/sql-createfunction.html
https://stackoverflow.com/questions/4547672/return-multiple-fields-as-a-record-in-postgresql-with-pl-pgsql

**Comment by smnorris** [comment]
There may be a way to get the geoms out of the table but it seems like currently I have to do something like this:
```
-- find streams and measures
select stream_crossing_id, blue_line_key, downstream_route_measure
FROM bcfishpass.crossings
WHERE stream_crossing_id IN (50152,62515,50181,50185,50261,62423,62516,197533,197534,197542,197555);

-- then copy the results into this query
SELECT 62515 as stream_crossing_id, * FROM FWA_WatershedAtMeasure(356547712,112)
UNION ALL
SELECT 197542 as stream_crossing_id, FWA_WatershedAtMeasure(356519898, 958.3895465360829)
UNION ALL
SELECT 197534 as stream_crossing_id, FWA_WatershedAtMeasure(356568905, 1074.3362791686563)
UNION ALL
SELECT 50261 as stream_crossing_id, FWA_WatershedAtMeasure(356556217, 350)
UNION ALL
SELECT 50181 as stream_crossing_id, FWA_WatershedAtMeasure(356568403, 3218)
UNION ALL
SELECT 197555 as stream_crossing_id, FWA_WatershedAtMeasure(356568300, 888.1906381072803)
UNION ALL
SELECT 50152 as stream_crossing_id, FWA_WatershedAtMeasure(356535965, 195)
UNION ALL
SELECT 50185 as stream_crossing_id, FWA_WatershedAtMeasure(356568403, 206)
UNION ALL
SELECT 62423 as stream_crossing_id, FWA_WatershedAtMeasure(356528119, 9245)
UNION ALL
SELECT 197533 as stream_crossing_id, FWA_WatershedAtMeasure(356563721, 599.0783428124566)
```

**Comment by smnorris** [comment]
hmm, maybe there are cases where multiple rows are needed, above returns this, but presumably this is an error.
```
ERROR:  more than one row returned by a subquery used as an expression
CONTEXT:  PL/pgSQL function fwa_watershedatmeasure(integer,double precision) line 26 at RETURN QUERY
```

**Comment by stephenhillier** [comment]
Hi Simon, great work on this library and thanks for sharing. The integration with WA/ID/MT data is really neat.

We've also done some work estimating upstream areas of watersheds and sometimes we find it useful to have a table of results (specifically a table of fundamental watersheds that are upstream from a point) that we can join with other data as needed.  Not necessarily suggesting this as a feature request (I'm still just exploring everything), just offering my two cents.

As for the comment above, would this work (I substituted ST_Area in to make the results more readable)? 
```
select stream_crossing_id, ST_Area(geom) from
  (
      select stream_crossing_id, blue_line_key, downstream_route_measure
      FROM   bcfishpass.crossings
      WHERE  stream_crossing_id IN (50152,62515,50181,50185,50261,62423,62516,197533,197534,197542,197555);

  ) fc
left join lateral
  (
    select geom from postgisftw.FWA_WatershedAtMeasure(blue_line_key, downstream_route_measure)
  ) ws on true;
```

**Comment by smnorris** [comment]
Trying the query with just 2 points, I do think you have to do the join on watershed codes. Unless the two points happen to be in the same fundamental watershed. I set max_parallel_workers_per_gather to zero because I've upgraded by db to pg13 and the watershed function will bail because it relies on `ST_Safe_Difference`.
```
postgis=# SET max_parallel_workers_per_gather = 0;
postgis=# select stream_crossing_id, ST_Area(geom) from
  (
      select stream_crossing_id, blue_line_key, downstream_route_measure
      FROM   bcfishpass.crossings
      WHERE  stream_crossing_id IN (50152,62515)

  ) fc
left join lateral
  (
    select geom from postgisftw.FWA_WatershedAtMeasure(blue_line_key, downstream_route_measure)
  ) ws on true;
 stream_crossing_id |      st_area
--------------------+-------------------
              50152 | 4447202.413615958
              62515 | 4447202.413615958
(2 rows)
```

**Comment by stephenhillier** [comment]
Hi @smnorris  I should have been more clear, I meant `left join lateral` could be a solution to your other comment above (apologies if you already solved that problem and didn't need help):
```
-- find streams and measures
select stream_crossing_id, blue_line_key, downstream_route_measure
etc...

-- then copy the results into this query
etc...
```

We have pg_tileserv working with a cache here https://apps.nrs.gov.bc.ca/gwells/

**Comment by smnorris** [comment]
@stephenhillier  - that is also a very nice interface for searching for geographic features. I will have to look into gwells and see if it can easily be modified to work with culverts or other arbitrary features.

**Comment by smnorris** [comment]
@stephenhillier - thanks for this tip, usage with LATERAL is included in draft documentation.
https://smnorris.github.io/fwapg/02_usage.html
