### ISSUE TITLE
fwa_locatealonginterval API function fails on columbia river

### ISSUE THREAD

**Issue by sebdalgarno** [smnorris/fwapg#42]
blue_line_key = 356570372

https://www.hillcrestgeo.ca/fwapg/functions/fwa_locatealonginterval/items.html?blue_line_key=356570372

works on other blue_line_keys, e.g. 
https://www.hillcrestgeo.ca/fwapg/functions/fwa_locatealonginterval/items.html?blue_line_key=356568123

**Comment by smnorris** [comment]
With only a couple of small exceptions, no ex-BC streams are included in FWA. You need to know the measures that are within the province.

Eg
https://www.hillcrestgeo.ca/fwapg/functions/fwa_locatealonginterval/items.html?blue_line_key=356570372&start_measure=1177478

This would may a lot more complicated if you want Rkms on the Kettle or other streams/rivers which meander back and forth across borders (or it might actually work for the BC portions as long as you give it a start_measure that is in BC, I haven't checked)

**Comment by sebdalgarno** [comment]
thansk @smnorris . this is interesting. If I get Columbia River from fwa_collection and whse_basemapping.fwa_stream_networks_sp it only returns the portion within BC. Just so I fully understand, why is fwa_locatealonginterval including US features?

**Comment by smnorris** [comment]
It shouldn't. What is the fwa_locatealonginterval request that returns US features?

**Comment by sebdalgarno** [comment]
sorry on second thought the above is not true - I was using the bbox arg for my study area. I understand now that fwapg includes the US portion

**Comment by smnorris** [comment]
I checked and my example wasn't a good one - the Kettle River *is* one of the trans-border streams included in FWA (USA between Midway and Grand Forks), it works fine.
https://www.hillcrestgeo.ca/fwapg/functions/fwa_locatealonginterval/items.html?blue_line_key=356570045&start_measure=58541

But only if your start measure is in BC.  And smaller streams that go back and forth across the border and aren't include in FWA geometries will not work.
