### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by smnorris** [smnorris/fwapg#57]
- descriptions for tables in `sql/tables/value_added`
- overviews of all provided functions `FWA_*`

**Comment by smnorris** [comment]
Draft docs for installation/setup and primary functions added.
@joethorley @newgraphenvironment - proof reads and comments/PRs are very welcome.

**Comment by NewGraphEnvironment** [comment]
This is glorious.  I haven't tried to update my version yet.  Looks like a huge evolution. Thank you.

Does it make sense to facilitate setup of a virt env with an `environment.yml` file to aid user setup of the environmental variables? 

Setting the variables in the past has been a massive sticking point for me that seems to be easily resolved with the yml file.

**Comment by smnorris** [comment]
Functionality and schema changes relative to v0.1.1 are fairly minor - but scripts and object names are tidier, the load script should be more robust... and the documentation is long overdue.

As far as providing a `conda` environment, I don't think that is necessary - Python isn't used and dependencies are now minimal. It is definitely presumed to be run on linux/mac/WSL where `make` will already be installed. 

Since the method for setting the environment variables will be the same for any of those systems I can expand on this section slightly: https://smnorris.github.io/fwapg/01_setup.html#environment-variables. But I'm fine with the docs for this presuming a familiarity with postgres setup and environment setup - that is better covered elsewhere.

**Comment by smnorris** [comment]
With all value added tables now more or less commented/described I'll close this for now.

**Comment by joethorley** [comment]
@smnorris - This is great! I'll let you know if I have any comments as I'm using and will do a PR where appropriate. Thanks!
